.. grid:: 1 2 2 4
   :gutter: 2

   .. grid-item-card::  Nuitka Commercial
      :class-item: nuitka-grid-offer nuitka-offer-commercial

       .. container:: nuitka-price

           € 250 / yr

       .. container:: nuitka-buy

         `Subscribe now » </stripe/checkout-commercial-subscription>`__

       - Commercial only Features

       - All your applications

       - Standard Support

   .. grid-item-card::  Nuitka Priority
      :class-item: nuitka-grid-offer nuitka-offer-priority

       .. container:: nuitka-price

           € 250 / yr

       .. container:: nuitka-buy

         `Subscribe now » </stripe/checkout-priority-subscription>`__

       - Best Support

       - Issues have **Priority**

       - **No** Commercial features


   .. grid-item-card::  Full Package
      :class-item: nuitka-grid-offer nuitka-offer-full-package

       .. container:: nuitka-price

           € 400 / yr

       .. container:: nuitka-buy

         `Subscribe now » </stripe/checkout-full-subscription>`__

       - Nuitka Commercial **included**

       - Nuitka Priority **included**


   .. grid-item-card::  Sponsor
      :class-item: nuitka-grid-offer nuitka-offer-sponsor

       .. container:: nuitka-price

           € 1000 / yr

       .. container:: nuitka-buy

         `Subscribe now » </stripe/checkout-sponsor-subscription>`__

       - Best Support

       - Nuitka Commercial

       - Roadmap Influence

       - Use Cases Priority

.. important::

   Click the buttons in the boxes above if Stripe payment works for you
   (bank transfer, credit card, SEPA debit charge, etc).
