#!/bin/bash

export PIPENV_VERBOSITY=-1
if [ -d ./Nuitka-develop ]
then
    exec python3 -m pipenv run python ./Nuitka-develop/bin/autoformat-nuitka-source $@
fi

exec python3 -m pipenv run python ../Nuitka-develop/bin/autoformat-nuitka-source $@
