.. important::

   Click the buttons in the boxes above for Stripe payment (bank
   transfer, credit card, SEPA debit charge, etc).

.. grid:: 1 2 2 3
   :gutter: 2

   .. grid-item-card::  Nuitka Commercial
      :class-item: nuitka-grid-offer nuitka-offer-commercial

       .. container:: nuitka-price

           € 250 / yr

       .. container:: nuitka-buy

         `Subscribe now » </stripe/checkout-commercial-subscription>`__

       - Commercial only Features

       - All your applications

       - Standard Support

   .. grid-item-card::  Full Package
      :class-item: nuitka-grid-offer nuitka-offer-full-package

       .. container:: nuitka-price

           € 400 / yr

       .. container:: nuitka-buy

         `Subscribe now » </stripe/checkout-full-subscription>`__

       - Nuitka Commercial **included**

       - Best Support **included**

       - Issues have **Priority**


   .. grid-item-card::  Sponsor
      :class-item: nuitka-grid-offer nuitka-offer-sponsor

       .. container:: nuitka-price

           € 1000 / yr

       .. container:: nuitka-buy

         `Subscribe now » </stripe/checkout-sponsor-subscription>`__

       - Best Support

       - Nuitka Commercial

       - Roadmap Influence

       - Use Cases Priority
