.. |DEBIAN_LOGO| image:: /images/debian.png

.. |UBUNTU_LOGO| image:: /images/ubuntu.png

.. |MINT_LOGO| image:: /images/mint.png

.. |CENTOS_LOGO| image:: /images/centos.png

.. |RHEL_LOGO| image:: /images/rhel.png

.. |FEDORA_LOGO| image:: /images/fedora.png

.. |SUSE_LOGO| image:: /images/opensuse.png

.. |WINDOWS_LOGO| image:: /images/windows.jpg

.. |ARCH_LOGO| image:: /images/arch.jpg

.. |GENTOO_LOGO| image:: /images/gentoo-signet.png

.. |GIT_LOGO| image:: /images/git.jpg

.. |COMING_SOON_CLOCK| image:: /images/coming-soon-clock.svg
   :width: 30%

.. |SUPPORTED_PYTHONS| replace::

   **Python 3** (3.4 — 3.13) and **Python 2** (2.6, 2.7)

.. |SHOPPING_CART_SYMBOL| raw:: html

   <i class="fa fa-fw fa-shopping-cart" aria-hidden="true"></i>

.. |DOWNLOAD_SYMBOL| raw:: html

   <i class="fa fa-fw fa-download" aria-hidden="true"></i>

.. |RESELLERS_SYMBOL| raw:: html

   <i class="fa fa-fw fa-handshake-o" aria-hidden="true"></i>

.. |DOCUMENTATION_SYMBOL| raw:: html

   <i class="fa fa-fw fa-book" aria-hidden="true"></i>

.. |PROTECTION_SYMBOL| raw:: html

   <i class="fa fa-fw fa-shield" aria-hidden="true"></i>

.. |VM_SYMBOL| raw:: html

   <i class="fa fa-fw fa-lock" aria-hidden="true"></i>

.. |SUPPORT_SYMBOL| raw:: html

   <i class="fa fa-fw fa-life-ring" aria-hidden="true"></i>

.. |CONTRIBUTE_SYMBOL| raw:: html

   <i class="fa fa-fw fa-cogs" aria-hidden="true"></i>

.. |NEWS_SYMBOL| raw:: html

   <i class="fa fa-fw fa-newspaper-o" aria-hidden="true"></i>

.. |BLOG_SYMBOL| raw:: html

   <i class="fa fa-fw fa-rss-square" aria-hidden="true"></i>

.. |STREAMING_SYMBOL| raw:: html

   <i class="fa fa-fw fa-video-camera" aria-hidden="true"></i>

.. |CREDITS_SYMBOL| raw:: html

   <i class="fa fa-fw fa-users" aria-hidden="true"></i>

.. |IMPRESSUM_SYMBOL| raw:: html

   <i class="fa fa-fw fa-info-circle" aria-hidden="true"></i>

..
   TODO: Use these

.. |MORE_SYMBOL| raw:: html

   <i class="fa fa-ellipsis-h" aria-hidden="true"></i>
