.. |DEBIAN_LOGO| image:: /images/debian.png

.. |UBUNTU_LOGO| image:: /images/ubuntu.png

.. |MINT_LOGO| image:: /images/mint.png

.. |CENTOS_LOGO| image:: /images/centos.png

.. |RHEL_LOGO| image:: /images/rhel.png

.. |FEDORA_LOGO| image:: /images/fedora.png

.. |SUSE_LOGO| image:: /images/opensuse.png

.. |WINDOWS_LOGO| image:: /images/windows.jpg

.. |ARCH_LOGO| image:: /images/arch.jpg

.. |GENTOO_LOGO| image:: /images/gentoo-signet.png

.. |GIT_LOGO| image:: /images/git.jpg

.. |SUPPORTED_PYTHONS| replace::

   **Python 3** (3.4 — 3.13) and **Python 2** (2.6, 2.7)

.. |SHOPPING_CART_SYMBOL| raw:: html

   <i class="fa fa-shopping-cart" aria-hidden="true"></i>
