name: Run visual regression tests

on:
  pull_request:
    branches: [main]

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        device: [desktop, mobile]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.11"

      - name: Cache Pipenv dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
          npm install
          pipenv run playwright install-deps

      - name: Start app for screenshots
        run: |
          export DEVELOPMENT_MODE=1
          pipenv run invoke update-docs
          pipenv run invoke site
          pipenv run invoke post-process
          nohup pipenv run invoke serve &
          sleep 5

      - name: Run visual regression tests
        run: |
          pipenv run pytest tests/regression.py -v \
            --browser=${{ matrix.browser }} \
            --device=${{ matrix.device }} \
            --tb=short
        continue-on-error: false
        id: tests

      - name: Upload current screenshots
        if: failure()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: current-${{ matrix.browser }}-${{ matrix.device }}-${{ github.run_number }}
          path: current/
          retention-days: 7

      - name: Upload diff images
        if: failure()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: diff-${{ matrix.browser }}-${{ matrix.device }}-${{ github.run_number }}
          path: diff/
          retention-days: 14

      - name: Workflow summary
        if: failure()
        run: |
          echo "### Visual Regression Test Failed" >> $GITHUB_STEP_SUMMARY
          echo "- Browser: ${{ matrix.browser }}" >> $GITHUB_STEP_SUMMARY
          echo "- Device: ${{ matrix.device }}" >> $GITHUB_STEP_SUMMARY
          echo "- Screenshots: [Artifacts tab](#)" >> $GITHUB_STEP_SUMMARY