name: Run visual regression tests

on:
  pull_request:
    branches: [main]

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        device: [desktop, mobile]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
          npm install

      - name: Install Playwright browsers
        run: pipenv run playwright install --with-deps ${{ matrix.browser }}

      - name: Start app for screenshots
        run: |
          export DEVELOPMENT_MODE=1
          pipenv run invoke update-docs
          pipenv run invoke site
          pipenv run invoke post-process
          nohup pipenv run invoke serve &
          sleep 5

      - name: Run visual regression tests
        run: |
          pipenv run pytest tests/regression.py -v \
            --browser=${{ matrix.browser }} \
            --device=${{ matrix.device }} \
            --tb=short
        continue-on-error: true
        id: tests

      - name: Upload current screenshots
        if: failure()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: current-${{ matrix.browser }}-${{ matrix.device }}-${{ github.run_number }}
          path: current/
          retention-days: 7

      - name: Upload diff images
        if: failure()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: diff-${{ matrix.browser }}-${{ matrix.device }}-${{ github.run_number }}
          path: diff/
          retention-days: 14
